name: MCONE-KnockIt
author: Domink Lippl
version: ${project.version}
main: eu.mcone.knockit.KnockIT
depend: [MCONE-BukkitCoreSystem, MCONE-GameAPI]

permissions:
  knockit:
    description: Root Permission
    children:
      knockit.set:
        description: Use the fishing rod
        children:
          knockit.set.spawn:
            description: Allows the player to set the spawn
      knockit.angel:
        description: Set wether Fishing Hook is used or not