name: MCONE-KnockIt
version: ${project.version}
authors: [Domink Lippl, Rufus Maiwald, Marvin Hülsmann]
main: eu.mcone.knockit.KnockIT
depend: [MCONE-GameSystem, MCONE-BukkitCoreSystem]

permissions:
  knockit:
    description: Root Permission
    children:
      knockit.set:
        description: Use the fishing rod
        children:
          knockit.set.spawn:
            description: Allows the player to set the spawn
      knockit.angel:
        description: Set wether Fishing Hook is used or not